const state = { track: null, passes: [], sample: true, index: 0, sourceName: 'VALLADO 00005' };
const $ = (id) => document.getElementById(id);
const canvas = $('orbitCanvas');
const ctx = canvas.getContext('2d');
const moonbitApiPromise = import('./moonsatkit.js').catch((error) => { console.error('MoonBit browser adapter failed to load', error); $('runtimeStatus').textContent = 'SAMPLE FALLBACK'; $('footerMessage').textContent = 'MOONBIT ADAPTER UNAVAILABLE · SAMPLE FALLBACK'; return null; });

function formatNumber(value, digits = 2) { if (!Number.isFinite(value)) return '—'; return value.toFixed(digits); }
function shortTime(text) { return text ? text.slice(11, 16) : '—'; }
function unwrapDate(text) { if (!text) return NaN; const normalized = text.includes('T') ? text : text.replace(' ', 'T'); return new Date(normalized.endsWith('Z') ? normalized : normalized + 'Z').getTime(); }
function parseCoordinates() { return state.track?.geometry?.coordinates || []; }
function project(lon, lat, width, height) { const pad = 18; return { x: pad + ((lon + 180) / 360) * (width - pad * 2), y: pad + ((90 - lat) / 180) * (height - pad * 2) }; }
function splitSegments(coords) { const segments = []; let segment = []; coords.forEach((point, index) => { if (index && Math.abs(point[0] - coords[index - 1][0]) > 180) { if (segment.length) segments.push(segment); segment = []; } segment.push(point); }); if (segment.length) segments.push(segment); return segments; }
function resizeCanvas() { const rect = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; canvas.width = Math.max(1, Math.floor(rect.width * ratio)); canvas.height = Math.max(1, Math.floor(rect.height * ratio)); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); drawMap(); }
function drawMap() { const width = canvas.clientWidth; const height = canvas.clientHeight; if (!width || !height) return; ctx.clearRect(0, 0, width, height); ctx.fillStyle = '#081114'; ctx.fillRect(0, 0, width, height); const pad = 18; ctx.strokeStyle = 'rgba(100, 157, 148, .15)'; ctx.lineWidth = 1; for (let lon = -180; lon <= 180; lon += 30) { const p = project(lon, 0, width, height); ctx.beginPath(); ctx.moveTo(p.x, pad); ctx.lineTo(p.x, height - pad); ctx.stroke(); } for (let lat = -60; lat <= 60; lat += 30) { const p = project(0, lat, width, height); ctx.beginPath(); ctx.moveTo(pad, p.y); ctx.lineTo(width - pad, p.y); ctx.stroke(); } ctx.strokeStyle = 'rgba(247, 185, 94, .32)'; ctx.setLineDash([4, 5]); const equator = project(0, 0, width, height); ctx.beginPath(); ctx.moveTo(pad, equator.y); ctx.lineTo(width - pad, equator.y); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle = 'rgba(93, 225, 207, .08)'; ctx.fillRect(pad, pad, width - pad * 2, height - pad * 2); splitSegments(parseCoordinates()).forEach((segment, segmentIndex) => { ctx.beginPath(); segment.forEach((point, index) => { const p = project(point[0], point[1], width, height); if (index === 0) ctx.moveTo(p.x, p.y); else ctx.lineTo(p.x, p.y); }); ctx.strokeStyle = segmentIndex % 2 ? '#f7b95e' : '#5de1cf'; ctx.lineWidth = 1.8; ctx.shadowColor = segmentIndex % 2 ? 'rgba(247,185,94,.42)' : 'rgba(93,225,207,.46)'; ctx.shadowBlur = 7; ctx.stroke(); ctx.shadowBlur = 0; }); const station = project(Number($('stationLon').value) || 0, Number($('stationLat').value) || 0, width, height); ctx.beginPath(); ctx.arc(station.x, station.y, 5, 0, Math.PI * 2); ctx.fillStyle = '#ff8067'; ctx.fill(); ctx.beginPath(); ctx.arc(station.x, station.y, 10, 0, Math.PI * 2); ctx.strokeStyle = 'rgba(255,128,103,.4)'; ctx.stroke(); const current = parseCoordinates()[state.index]; if (current) { const sat = project(current[0], current[1], width, height); ctx.beginPath(); ctx.arc(sat.x, sat.y, 5, 0, Math.PI * 2); ctx.fillStyle = '#f7b95e'; ctx.fill(); ctx.beginPath(); ctx.arc(sat.x, sat.y, 12, 0, Math.PI * 2); ctx.strokeStyle = 'rgba(247,185,94,.32)'; ctx.stroke(); } }
function updateMetrics() { const coords = parseCoordinates(); const point = coords[state.index]; if (!point) { $('canvasNoData').hidden = false; return; } $('canvasNoData').hidden = true; $('currentLon').textContent = formatNumber(point[0], 2); $('currentLat').textContent = formatNumber(point[1], 2); $('currentAlt').textContent = formatNumber(point[2], 0); $('catalogNumber').textContent = state.track?.properties?.catalog_number ?? '—'; const start = state.track?.properties?.start || ''; const step = state.track?.properties?.step_seconds || 0; const currentDate = unwrapDate(start) + state.index * step * 1000; $('timelineLabel').textContent = Number.isFinite(currentDate) ? new Date(currentDate).toISOString().slice(0, 19).replace('T', ' ') + ' UTC' : '—'; $('orbitState').textContent = point[2] > 160 ? 'TRACKING' : 'LOW ALTITUDE'; $('horizonState').textContent = point[1] > -5 ? 'VISIBLE BAND' : 'BELOW LOCAL'; drawMap(); }
function renderPasses() { const threshold = Number($('elevationFilter').value); $('elevationOutput').textContent = threshold + '°'; const visible = state.passes.filter(pass => pass.maximum_elevation_deg >= threshold); $('passCount').textContent = visible.length; $('passList').innerHTML = visible.length ? visible.map((pass, index) => '<article class="pass-card ' + (index === 0 ? 'primary' : '') + '"><div class="pass-card-head"><span>PASS ' + String(index + 1).padStart(2, '0') + '</span><strong>MAX ' + formatNumber(pass.maximum_elevation_deg, 1) + '°</strong></div><div class="pass-times"><div class="pass-time"><span>AOS</span><strong>' + shortTime(pass.aos) + '</strong></div><div class="pass-time"><span>TCA</span><strong>' + shortTime(pass.tca) + '</strong></div><div class="pass-time"><span>LOS</span><strong>' + shortTime(pass.los) + '</strong></div></div></article>').join('') : '<div class="empty-pass">当前仰角筛选下没有过境窗口。</div>'; }
function updateTrackView(track, passes, options) { state.track = track; state.passes = Array.isArray(passes) ? passes : []; state.sample = options.sample; state.index = 0; state.sourceName = options.label; const coords = track?.geometry?.coordinates || []; $('sourceLabel').textContent = '/ ' + options.label; $('runtimeStatus').textContent = options.status; $('footerMessage').textContent = options.footer; $('timeline').max = Math.max(0, coords.length - 1); $('timeline').value = 0; $('sampleCount').textContent = coords.length + ' samples'; const elevations = coords.map(p => p[2]).filter(Number.isFinite); $('altitudeRange').textContent = elevations.length ? formatNumber(Math.min(...elevations), 0) + ' — ' + formatNumber(Math.max(...elevations), 0) + ' km' : '—'; updateMetrics(); renderPasses(); }
function setValidation(ok, text) { const message = $('validationMessage'); message.classList.toggle('invalid', !ok); message.textContent = text; }
async function validateTle() { const line1 = $('tleLine1').value.trim(); const line2 = $('tleLine2').value.trim(); const api = await moonbitApiPromise; if (!api?.moon_sat_validate_tle) { setValidation(false, 'MoonBit JS 适配层未加载，当前仅可查看样例'); $('footerMessage').textContent = 'TLE CHECK FAILED · SAMPLE FALLBACK'; return false; } const result = JSON.parse(api.moon_sat_validate_tle(line1, line2)); if (result.ok) { setValidation(true, 'MoonBit SGP4 适配层已通过 TLE 校验'); $('catalogNumber').textContent = result.catalog_number; $('footerMessage').textContent = 'TLE CHECK PASSED · MOONBIT JS'; } else { setValidation(false, '校验失败：' + result.error); $('footerMessage').textContent = 'TLE CHECK FAILED · MOONBIT JS'; } return result.ok; }
function normalizeFromTime(value) { const text = value.trim().replace('T', ' '); const date = new Date(text.replace(' ', 'T') + (text.endsWith('Z') ? '' : 'Z')); if (!Number.isFinite(date.getTime())) throw new Error('起始时间格式无效，请使用 YYYY-MM-DD HH:MM:SS'); return date.toISOString().slice(0, 19).replace('T', ' '); }
function readNumber(id, label) { const value = Number($(id).value); if (!Number.isFinite(value)) throw new Error(label + '必须是数字'); return value; }
function setCalculating(busy) { const button = $('calculateButton'); button.disabled = busy; button.querySelector('span').textContent = busy ? '…' : '▶'; button.lastChild.textContent = busy ? ' 计算中…' : ' 计算轨迹'; }
async function calculateTrack() { const api = await moonbitApiPromise; if (!api?.moon_sat_track_geojson || !api?.moon_sat_passes_json) throw new Error('MoonBit JS 适配层未加载，请检查 web/moonsatkit.js'); const line1 = $('tleLine1').value.trim(); const line2 = $('tleLine2').value.trim(); const from = normalizeFromTime($('fromTime').value); const durationHours = Number($('durationValue').value); const stepSeconds = Number($('stepValue').value); const latitude = readNumber('stationLat', '纬度'); const longitude = readNumber('stationLon', '经度'); const altitude = readNumber('stationAlt', '海拔'); const minimumElevation = Number($('elevationFilter').value); const validation = JSON.parse(api.moon_sat_validate_tle(line1, line2)); if (!validation.ok) throw new Error(validation.error); const trackResult = JSON.parse(api.moon_sat_track_geojson(line1, line2, from, durationHours * 3600, stepSeconds)); if (!trackResult.ok) throw new Error(trackResult.error); const passResult = JSON.parse(api.moon_sat_passes_json(line1, line2, latitude, longitude, altitude, from, durationHours, minimumElevation)); if (!passResult.ok) throw new Error(passResult.error); updateTrackView(trackResult.track, passResult.passes, { sample: false, label: 'NORAD ' + validation.catalog_number, status: 'MOONBIT JS', footer: 'CALCULATION COMPLETE · SGP4' }); setValidation(true, 'MoonBit SGP4 适配层已通过 TLE 校验'); }
async function calculateWithFeedback() { setCalculating(true); $('footerMessage').textContent = 'CALCULATING · MOONBIT SGP4'; try { await calculateTrack(); } catch (error) { setValidation(false, '计算失败：' + error.message); $('footerMessage').textContent = 'CALCULATION FAILED'; console.error(error); } finally { setCalculating(false); } }
function downloadTrack() { if (!state.track) return; const blob = new Blob([JSON.stringify(state.track, null, 2)], {type: 'application/geo+json'}); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'moonsatkit-track.geojson'; link.click(); URL.revokeObjectURL(url); $('footerMessage').textContent = 'EXPORT COMPLETE · GEOJSON'; }
async function loadFiles() { try { const [track, passes] = await Promise.all([fetch('data/vallado-track.geojson').then(r => r.json()), fetch('data/vallado-passes.json').then(r => r.json())]); updateTrackView(track, passes, { sample: true, label: 'VALLADO 00005', status: 'LOCAL SAMPLE', footer: 'READY · SAMPLE DATA LOADED' }); } catch (error) { $('canvasNoData').hidden = false; $('footerMessage').textContent = 'DATA LOAD ERROR'; console.error(error); } }
$('timeline').addEventListener('input', event => { state.index = Number(event.target.value); updateMetrics(); }); $('elevationFilter').addEventListener('input', renderPasses); $('validateButton').addEventListener('click', () => { validateTle().catch(error => { setValidation(false, '校验失败：' + error.message); }); }); $('calculateButton').addEventListener('click', calculateWithFeedback); $('resetButton').addEventListener('click', loadFiles); $('downloadButton').addEventListener('click', downloadTrack); window.addEventListener('resize', resizeCanvas); ['stationLat', 'stationLon', 'stationAlt'].forEach(id => $(id).addEventListener('input', drawMap));
$('geojsonFile').addEventListener('change', async event => { const file = event.target.files?.[0]; if (!file) return; try { const track = JSON.parse(await file.text()); if (track?.geometry?.type !== 'LineString') throw new Error('需要 LineString GeoJSON'); updateTrackView(track, state.passes, { sample: false, label: file.name.toUpperCase(), status: 'IMPORTED GEOJSON', footer: 'IMPORTED · GEOJSON TRACK LOADED' }); } catch (error) { $('footerMessage').textContent = 'IMPORT FAILED · INVALID GEOJSON'; console.error(error); } });
setInterval(() => { $('utcClock').textContent = new Date().toISOString().slice(11, 19); }, 1000); $('utcClock').textContent = new Date().toISOString().slice(11, 19); loadFiles(); requestAnimationFrame(resizeCanvas);
